os:
  - linux
  - osx
  # Secret environment variables not yet supported for Windows.
  # See https://travis-ci.community/t/windows-instances-hanging-before-install/250.
  # - windows

dist: trusty
sudo: false

language: node_js
node_js:
  - 8
  - 10
  - node

cache:
  directories:
    - "$HOME/.npm"

install:
  # Run `npm install`, if `npm ci` fails, to work around old npm versions' not supporting `npm ci`.
  - npm ci || npm install;

script:
  - npm test;
